name: sheaf-lang-demo
version: 0.1.0.0
author: "Arnaud Spiwack"

spec-version: 0.39.0

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- containers
- diagnose
- megaparsec >= 9.0
- optparse-applicative
- parser-combinators >= 1.3
- prettyprinter

library:
  source-dirs: src

executables:
  sheaf-lang-demo:
    main: Main.hs
    source-dirs: app
    dependencies:
    - sheaf-lang-demo

ghc-options: "-Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wnoncanonical-monad-instances -frefinement-level-hole-fits=1"
