{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ImpredicativeTypes #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE StandaloneKindSignatures #-}
{-# LANGUAGE TypeAbstractions #-}
{-# LANGUAGE TypeFamilies #-}

-- | This module defines a category of sheaves over 'Arith.Expr' which makes
-- 'Arith.TBool' the coproduct of 'Unit' and 'Unit' in the category of sheaves.
-- This is exactly as much as we need to share control flow with our simple
-- category 'Arith.Expr'.
--
-- Sheaves form a full subcategory of the category of presheaves. That is the
-- arrows between two sheaves @p@ and @q@ are the natural transformation @forall
-- i. p i -> q i@.
--
-- Most of the presentation is generic and could be abstracted over the
-- topology.
module Sheaf where

import Arith qualified
import Data.Kind
import Presheaf

-- | This presentation of sheaf is largely inspired by Pierre-Marie Pédrot's work
-- (see https://www.p%C3%A9drot.fr/drafts/shtuck.pdf). At the end of the day it
-- turns out to be pretty standard definition. Rather close to the textbook
-- presentation with sheaves and matching families. What I take from
-- Pierre-Marie Pédrot's work is that it's not necessary that the covers are
-- sieves, arbitrary types work.
--
-- All in all, I think it ends up being pretty standard. It just not obvious
-- from the most accessible literature.
--
-- The important feature of this presentation is that it avoids speaking about
-- the pullback of a sieve, which is a very dependent-type-y notion, which
-- wouldn't translate well into Haskell.
class (Presheaf p) => Sheaf p where
  -- | This type has a hint of dependent type. A @forall c.@ followed by a single
  -- ton type at @c@ (here in the form of @'KnownCover' c@ because it's usually
  -- easier to let the typechecker handle @c@) is the same as a depdendent
  -- product @Π c.@
  glueOracle :: forall {i} (c :: Cover i) j. (KnownCover c) => Arith.Expr j i -> (Gen c -> p j) -> p j

-- | @'Sheafify' p@ is the “smallest” sheaf generated by @p@ (in particular it is
-- isomorphic @p@ if @p@ is already a sheaf). Following Pierre-Marie Pédrot,
-- again, it simply takes the form of a free monad.
type Sheafify :: Presh -> Presh
data Sheafify p i where
  Ret :: p i -> Sheafify p i
  Oracle :: forall p {i} (c :: Cover i) j. (KnownCover c) => Arith.Expr j i -> (Gen c -> Sheafify p j) -> Sheafify p j

instance (Presheaf p) => Presheaf (Sheafify p) where
  pb f (Ret x) = Ret (pb f x)
  pb f (Oracle k o) = Oracle (f `Arith.compose` k) (pb f . o)

instance (Presheaf p) => Sheaf (Sheafify p) where
  glueOracle = Oracle

-- | The universal property of sheafification. Any map from @p@ to a sheaf @q@
-- factors through a (unique) map from @'Sheafify' p@ to @q@.
liftSh :: (Presheaf p, Sheaf q) => (forall j. p j -> q j) -> Sheafify p i -> q i
liftSh f (Ret x) = f x
liftSh f (Oracle k o) = glueOracle k $ \c -> liftSh f (o c)

-- | Limits of sheaves are sheaves
instance (Sheaf p, Sheaf q) => Sheaf (PProd p q) where
  glueOracle k o = MkPProd (glueOracle k (fstp . o), glueOracle k (sndp . o))
    where

-- | Limits of sheaves are sheaves
instance Sheaf PUnit where
  glueOracle _ _ = MkPUnit

-- | The exponential object in the category of presheaves is a sheaf if the
-- codomain is a sheaf. Because of the global behaviour of the exponential
-- (where fibers define functions at every object), we need the global behaviour
-- of the sheaf condition ('glueOracle' or equivalently, in our case,
-- 'glueIfThenElse'). Proving that functions are sheaves puts the most
-- constraint on the definition. In textbook proof this is one of the place
-- where the pullback of sieves seems invoked in a fundamental way.
--
-- It's occasionally quite useful that @p@ need only be a presheaf. In
-- particular we will use a variant of this property in the interpreter.
instance (Presheaf p, Sheaf q) => Sheaf (PFun p q) where
  glueOracle k o = MkPFun $ \l x -> glueOracle (l `Arith.compose` k) $ \c -> runPFun (o c) l x

-- | Sums (coproducts) aren't sheaves. However the sheafification of sums
-- happens to be the appropriate coproducts in the category of sheaves.
--
-- For data types such as lists, it means that we need to wrap every recursive
-- calls with a sheafification. It's slightly easier to inline sheafification
-- in the datatype definition, as an extra constructor (this is yet another idea
-- that I stole from Pierre-Marie Pédrot).
data ShList p i where
  ShNil :: ShList p i
  ShCons :: p i -> ShList p i -> ShList p i
  ListOracle :: forall p {i} (c :: Cover i) j. (KnownCover c) => Arith.Expr j i -> (Gen c -> ShList p j) -> ShList p j

instance (Presheaf p) => Presheaf (ShList p) where
  pb _f ShNil = ShNil
  pb f (ShCons x xs) = ShCons (pb f x) (pb f xs)
  pb f (ListOracle k o) = ListOracle (f `Arith.compose` k) (pb f . o)

instance (Presheaf p) => Sheaf (ShList p) where
  glueOracle k o = ListOracle k o

-- | To illustrate that lists behaves as lists, here are a few variants over
-- pattern-matching on lists.
caseShList0 :: forall p i. ShList p i -> Sheafify (PSum PUnit (PProd p (ShList p))) i
caseShList0 ShNil = Ret (MkPSum (Left MkPUnit))
caseShList0 (ShCons x xs) = Ret (MkPSum (Right (MkPProd (x, xs))))
caseShList0 (ListOracle k o) = Oracle k $ \c -> caseShList0 (o c)

-- | See 'caseShList0'.
caseShList1 :: forall p q i. (Presheaf p, Sheaf q) => ShList p i -> (forall j. PSum PUnit (PProd p (ShList p)) j -> q j) -> q i
caseShList1 l f = liftSh f (caseShList0 l)

-- | See 'caseShList0'.
caseShList2 ::
  forall γ p q i.
  (Presheaf γ, Presheaf p, Sheaf q) =>
  γ i ->
  (forall j. γ j -> ShList p j) ->
  (forall j. γ j -> PSum PUnit (PProd p (ShList p)) j -> q j) ->
  q i
caseShList2 γ0 scrut f = switch $ MkPProd (scrut γ0, γ0)
  where
    switch :: forall j. (PProd (ShList p) γ) j -> q j
    switch = openLamP $ \l -> caseShList1 l $ \cases
      (MkPSum (Left MkPUnit)) -> MkPFun $ \_k γ -> f γ (MkPSum (Left MkPUnit))
      (MkPSum (Right (MkPProd (h, t)))) -> MkPFun $ \k γ -> f γ (MkPSum (Right (MkPProd (pb k h, pb k t))))

---------------------------------------------------------------------------
--
-- Specific to the topology
--
---------------------------------------------------------------------------

-- | 'glueIfThenElse' is a complete characterisation of our sheaves. We could
-- have taken this as our definition of sheaves. I chose the definition in term
-- of covers because it can more easily be abstracted. So I use 'glueOracle' in
-- this file for things which can be proved generically for sheaves, and
-- 'glueIfThenElse' for things which only holds in our particular topology.
--
-- Note how the type of 'glueIfThenElse' is really isomorphic to the type of
-- 'glueOracle' with our choice of toplogy.
glueIfThenElse :: (Sheaf p) => Arith.Expr i Arith.TBool -> p i -> p i -> p i
glueIfThenElse b t f = glueOracle @_ @BoolCover b $ \c -> case c of
  TrueCovers -> t
  FalseCovers -> f

-- | A concrete property of our sheaves is that the fiber at 'Arith.TBool' is
-- completely determined by the fiber at 'Arit.TUnit'.
glueBool :: (Sheaf p) => (p 'Arith.TUnit, p 'Arith.TUnit) -> p 'Arith.TBool
glueBool (t, f) = glueIfThenElse Arith.Id (pb Arith.Unit t) (pb Arith.Unit f)

-- | This holds in every presheaf, but becomes an isomorphism (via 'glueBool')
-- in our sheaves.
splitBool :: (Presheaf p) => p 'Arith.TBool -> (p 'Arith.TUnit, p 'Arith.TUnit)
splitBool b = (pb Arith.BTrue b, pb Arith.BFalse b)

-- | Each element of @'Cover' i@ is the name of a cover of object @i@. In our
-- case we have only one: we can cover 'Arith.TBool' with arrows 'Arith.BTrue'
-- and 'Arith.BFalse'.
data Cover i where
  BoolCover :: Cover Arith.TBool

-- | Singleton types for 'Cover'.
type SCover :: Cover i -> Type
data SCover c where
  SBoolCover :: SCover BoolCover

class KnownCover c where
  knownCover :: SCover c

instance KnownCover BoolCover where
  knownCover = SBoolCover

-- | Maps each cover name to the type of its generators.
type Gen :: Cover i -> Type
data Gen c where
  TrueCovers :: Gen BoolCover
  FalseCovers :: Gen BoolCover

-- | Because we don't introduce any new colimits (that is, all the colimits that
-- we force in the sheaf categories are already colimits in the base category),
-- the representable presheaves (aka sheaves of the form @'Y' i@) are sheaves. A
-- site with the property that representables are sheaves is called
-- /subcanonical/.
--
-- Note that this is the one place where 'Arith.IfThenElse' is used, so this is
-- where we connect the control flow of the category of sheaves, and of the
-- arithmetic circuits.
instance Sheaf (Y i) where
  glueOracle @c k o = case knownCover @c of
    SBoolCover -> MkY $ Arith.IfThenElse k (unY (o TrueCovers)) (unY (o FalseCovers))

-- | Lifts if-then-else to sheaves. This is what we need sheaves for. Without
-- this Booleans are only evaluated after lowering to the base category,
-- preventing us from branching of @isZero@, say.
ifThenElseSh :: (Sheaf p) => Y 'Arith.TBool i -> p i -> p i -> p i
ifThenElseSh (MkY b) = glueIfThenElse b
